### ISSUE TITLE
Lock down the version of terra-base and terra-popup for terra-consumer-nav

### ISSUE THREAD

**Issue by kafkahw** [cerner/terra-consumer#113]
# Issue Description
terra-base 2.11.0 adds new styles to link pseudo classes which affects all anchor links in our app. We should lock down the version of terra-base to 2.10.0 and other dependencies that consume terra-base.
See this issue for more details: https://github.com/cerner/terra-core/issues/1212

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
terra-consumer-nav specifies terra-base to be 2.10.0 and terra-popup to be 1.19.0.

NOTE: the reason we need to lock down terra-popup is because terra-popup 1.20.0 depends on terra-hookshot 1.8.0 that depends on terra-base 2.11.0.

**Comment by alex-bezek** [comment]
If terra-base 2.10.0 causes something bad in your application, you can just lock it down explicitly in your package.json. Locking to 2.10.0 in your app still fits within the constraints of this package.

We won't be locking these to lower versions, infact we will be upgrading them all here shortly as terra-core's react 16 upgrade finalizes and we also upgrade.

**Comment by kafkahw** [comment]
it doesn't make any sense to lock down the version of terra-base in our app because it's not one of our dependencies.
And to be honest, I even tried to add terra-base into our dependencies (though it doesn't make sense) and lock it down 2.10.0 and still got the issue. It caused by the version of terra-popup that indirectly consumes terra-base 2.11.0. Should I keep adding terra-popup into our dependencies and lock the version of it even though it's not a dependency of our app? That way we'll just keep more and more deps which are not directly consumed by our app. I don't think that's a good practice.
If by locking you mean modifying the package-lock.json file in healthealstic-react, then it won't affect healthelastic's package-lock.json file. 
No matter what, terra-consumer as a library should make sure that all its consumers get the right package installed. I don't think it should be handled by lib consumers.

**Comment by alex-bezek** [comment]
We would have to find each terra-core item that consumes terra-base, find the version that locks to 2.10.0 for each, and lock them. This would mean to upgrade any of them we have to go through this manual resolution process again. The recommended process for us is to let terra components float as anytime there is a terra-base update each terra-component will be upgraded. In general its also bad for us to lock down packages to a specific version as if the consumer also uses that component it could have different versions.

Terra is patching the existing button version to ignore the global styles on the link style button.

As for your profile links pop up changing from black to blue, this is intentional as it aligns with our OCS changes. I spoke with our UX designer and this is an intentional change. If you need all links to not align with OCS for a particular color, you can override the css variable.
